-- Insert mock appointment data for insurer dashboard scenarios

INSERT INTO appointments (
  id,
  customer_name,
  customer_email,
  customer_phone,
  shop_id,
  shop_name,
  service_type,
  damage_type,
  appointment_date,
  appointment_time,
  status,
  job_status,
  ai_recommended_repair,
  ai_confidence_score,
  ai_assessment_details,
  requires_adas_calibration,
  adas_calibration_reason,
  driver_view_obstruction,
  is_insurance_claim,
  insurer_name,
  vehicle_info,
  damage_photos,
  total_cost,
  job_started_at,
  job_completed_at,
  completion_proof_path,
  invoice_file_path,
  completion_documents_verified,
  notes,
  additional_notes
) VALUES 

-- Scenario 1: Completed job with ADAS recalibration proof
(
  'a1a1a1a1-1111-1111-1111-111111111111',
  'Sarah Johnson',
  'sarah.johnson@email.com',
  '+1-555-0123',
  'shop-001',
  'Elite Auto Glass',
  'replacement',
  'windshield_replacement',
  CURRENT_DATE - INTERVAL '3 days',
  '10:00:00',
  'completed',
  'completed',
  'replacement',
  0.95,
  '{"damage_assessment": "Large crack extending across driver view area", "repair_feasibility": "Not repairable due to size and location", "estimated_time": "2-3 hours", "parts_needed": ["OEM windshield", "calibration equipment"], "fraud_risk": "low", "confidence_factors": ["clear damage photos", "consistent damage description", "verified VIN"]}',
  true,
  'Advanced Driver Assistance Systems (ADAS) detected - requires recalibration after windshield replacement',
  true,
  true,
  'StateFarm Insurance',
  '{"make": "Tesla", "model": "Model 3", "year": 2022, "vin": "5YJ3E1EA8NF123456", "color": "Pearl White", "mileage": 25000}',
  ARRAY['damage-photo-1.jpg', 'damage-photo-2.jpg'],
  850.00,
  NOW() - INTERVAL '3 days 1 hour',
  NOW() - INTERVAL '3 days',
  'completion-proofs/tesla-adas-calibration-cert.pdf',
  'invoices/tesla-windshield-invoice.pdf',
  true,
  'ADAS calibration completed successfully. All safety systems operational.',
  'Customer reported excellent service. ADAS recalibration certificate provided.'
),

-- Scenario 2: Job flagged for fraud risk due to VIN mismatch
(
  'b2b2b2b2-2222-2222-2222-222222222222',
  'Michael Rodriguez',
  'mrodriguez@email.com',
  '+1-555-0456',
  'shop-003',
  'Quick Fix Auto Glass',
  'repair',
  'chip_repair',
  CURRENT_DATE - INTERVAL '1 day',
  '14:30:00',
  'pending_review',
  'scheduled',
  'chip_repair',
  0.72,
  '{"damage_assessment": "Small chip in windshield", "repair_feasibility": "Repairable with resin injection", "estimated_time": "45 minutes", "fraud_risk": "high", "fraud_indicators": ["VIN mismatch with policy", "damage photos show different vehicle color", "appointment scheduled immediately after policy activation"], "confidence_factors": ["unclear damage photos", "inconsistent vehicle details"]}',
  false,
  null,
  false,
  true,
  'AllState Insurance',
  '{"make": "Honda", "model": "Civic", "year": 2019, "vin": "2HGFC2F59KH123789", "color": "Silver", "mileage": 45000}',
  ARRAY['suspicious-damage-1.jpg'],
  125.00,
  null,
  null,
  null,
  null,
  false,
  'FRAUD ALERT: VIN does not match policy records. Vehicle color discrepancy noted.',
  'Requires manual verification before proceeding. VIN check recommended.'
),

-- Scenario 3: AI correctly assessed as repair and completed successfully
(
  'c3c3c3c3-3333-3333-3333-333333333333',
  'Jennifer Chen',
  'j.chen@email.com',
  '+1-555-0789',
  'shop-002',
  'Precision Glass Services',
  'repair',
  'chip_repair',
  CURRENT_DATE - INTERVAL '2 days',
  '09:15:00',
  'completed',
  'completed',
  'chip_repair',
  0.89,
  '{"damage_assessment": "Small star-shaped chip, 15mm diameter", "repair_feasibility": "Excellent candidate for resin repair", "estimated_time": "30-45 minutes", "fraud_risk": "low", "confidence_factors": ["clear damage photos", "damage size within repairable limits", "no driver view obstruction", "verified customer history"]}',
  false,
  null,
  false,
  true,
  'Geico Insurance',
  '{"make": "Toyota", "model": "Camry", "year": 2020, "vin": "4T1G11AK8LU123456", "color": "Midnight Black", "mileage": 32000}',
  ARRAY['chip-damage-clear.jpg'],
  95.00,
  NOW() - INTERVAL '2 days 30 minutes',
  NOW() - INTERVAL '2 days',
  'completion-proofs/camry-repair-complete.jpg',
  'invoices/camry-chip-repair-invoice.pdf',
  true,
  'Perfect repair execution. Chip completely sealed and invisible.',
  'AI assessment was spot-on. Customer very satisfied with repair quality.'
),

-- Scenario 4: Replacement job with OEM parts requirement
(
  'd4d4d4d4-4444-4444-4444-444444444444',
  'Robert Williams',
  'rwilliams@email.com',
  '+1-555-0321',
  'shop-001',
  'Elite Auto Glass',
  'replacement',
  'windshield_replacement',
  CURRENT_DATE,
  '11:00:00',
  'in_progress',
  'in_progress',
  'replacement',
  0.93,
  '{"damage_assessment": "Multiple cracks radiating from impact point", "repair_feasibility": "Beyond repair - requires replacement", "estimated_time": "2.5 hours", "parts_needed": ["OEM windshield with rain sensor"], "fraud_risk": "low", "oem_required": true, "confidence_factors": ["extensive damage documented", "luxury vehicle requires OEM"]}',
  true,
  'BMW requires OEM windshield for proper ADAS function',
  true,
  true,
  'Progressive Insurance',
  '{"make": "BMW", "model": "X5", "year": 2023, "vin": "5UXCR6C09N9123456", "color": "Alpine White", "mileage": 8500}',
  ARRAY['bmw-windshield-damage-1.jpg', 'bmw-windshield-damage-2.jpg'],
  1250.00,
  NOW() - INTERVAL '2 hours',
  null,
  null,
  null,
  false,
  'OEM windshield ordered. Installation in progress with ADAS pre-calibration.',
  'High-end vehicle requires OEM parts per manufacturer specifications.'
),

-- Scenario 5: Emergency mobile service completed
(
  'e5e5e5e5-5555-5555-5555-555555555555',
  'Lisa Anderson',
  'landerson@email.com',
  '+1-555-0654',
  'shop-mobile-01',
  'Mobile Glass Pro',
  'repair',
  'crack_repair',
  CURRENT_DATE - INTERVAL '5 hours',
  '16:45:00',
  'completed',
  'completed',
  'crack_repair',
  0.85,
  '{"damage_assessment": "6-inch stress crack from temperature change", "repair_feasibility": "Repairable with resin injection", "estimated_time": "1 hour", "mobile_service": true, "fraud_risk": "low", "confidence_factors": ["weather-related damage pattern", "immediate service request"]}',
  false,
  null,
  false,
  true,
  'Farmers Insurance',
  '{"make": "Ford", "model": "Explorer", "year": 2021, "vin": "1FM5K8D87MGA12345", "color": "Agate Black", "mileage": 28000}',
  ARRAY['ford-crack-repair.jpg'],
  160.00,
  NOW() - INTERVAL '4 hours',
  NOW() - INTERVAL '3 hours',
  'completion-proofs/mobile-repair-complete.jpg',
  'invoices/mobile-service-invoice.pdf',
  true,
  'Mobile service completed at customer location. Crack successfully repaired.',
  'Emergency mobile service due to safety concern. Fast response time appreciated.'
);