-- Add more jobs with different statuses for all shops to ensure visibility across all filters

INSERT INTO appointments (
  customer_name,
  customer_email,
  customer_phone,
  shop_id,
  shop_name,
  service_type,
  damage_type,
  appointment_date,
  appointment_time,
  status,
  job_status,
  ai_recommended_repair,
  ai_confidence_score,
  ai_assessment_details,
  requires_adas_calibration,
  adas_calibration_reason,
  driver_view_obstruction,
  is_insurance_claim,
  insurer_name,
  vehicle_info,
  damage_photos,
  total_cost,
  job_started_at,
  job_completed_at,
  completion_proof_path,
  invoice_file_path,
  completion_documents_verified,
  notes,
  additional_notes
) VALUES 

-- SCHEDULED JOBS (multiple for each shop)
(
  'David Thompson',
  'david.thompson@email.com',
  '+1-555-1001',
  'shop-001',
  'Elite Auto Glass',
  'replacement',
  'windshield_replacement',
  CURRENT_DATE + INTERVAL '1 day',
  '09:00:00',
  'confirmed',
  'scheduled',
  'replacement',
  0.91,
  '{"damage_assessment": "Large impact crack", "repair_feasibility": "Requires replacement", "fraud_risk": "low"}',
  true,
  'Mercedes requires ADAS recalibration',
  true,
  true,
  'Sieger Insurance',
  '{"make": "Mercedes", "model": "C-Class", "year": 2021, "vin": "WDDGF4HB8MR123456", "color": "Black", "mileage": 35000}',
  ARRAY['mercedes-damage.jpg'],
  995.00,
  null,
  null,
  null,
  null,
  false,
  'Scheduled for tomorrow morning. Customer confirmed availability.',
  'ADAS calibration required after windshield replacement.'
),
(
  'Maria Garcia',
  'maria.garcia@email.com', 
  '+1-555-1002',
  'shop-002',
  'Precision Glass Services',
  'repair',
  'chip_repair',
  CURRENT_DATE + INTERVAL '2 days',
  '14:00:00',
  'confirmed',
  'scheduled',
  'chip_repair',
  0.87,
  '{"damage_assessment": "Small chip near edge", "repair_feasibility": "Good candidate for repair", "fraud_risk": "low"}',
  false,
  null,
  false,
  true,
  'Sieger Insurance',
  '{"make": "Nissan", "model": "Altima", "year": 2019, "vin": "1N4AL3AP4KC123456", "color": "Silver", "mileage": 42000}',
  ARRAY['nissan-chip.jpg'],
  89.00,
  null,
  null,
  null,
  null,
  false,
  'Appointment confirmed for Thursday afternoon.',
  'Simple chip repair, no special requirements.'
),
(
  'James Wilson',
  'james.wilson@email.com',
  '+1-555-1003', 
  'shop-003',
  'Quick Fix Auto Glass',
  'repair',
  'crack_repair',
  CURRENT_DATE + INTERVAL '3 days',
  '11:30:00',
  'confirmed',
  'scheduled',
  'crack_repair',
  0.83,
  '{"damage_assessment": "Stress crack from temperature", "repair_feasibility": "Repairable", "fraud_risk": "low"}',
  false,
  null,
  false,
  true,
  'Sieger Insurance',
  '{"make": "Hyundai", "model": "Elantra", "year": 2020, "vin": "KMHL14JA1LA123456", "color": "White", "mileage": 28000}',
  ARRAY['hyundai-crack.jpg'],
  135.00,
  null,
  null,
  null,
  null,
  false,
  'Friday appointment scheduled.',
  'Weather-related crack repair needed.'
),
(
  'Amanda Rodriguez',
  'amanda.rodriguez@email.com',
  '+1-555-1004',
  'shop-mobile-01',
  'Mobile Glass Pro', 
  'repair',
  'chip_repair',
  CURRENT_DATE + INTERVAL '1 day',
  '16:00:00',
  'confirmed',
  'scheduled',
  'chip_repair',
  0.92,
  '{"damage_assessment": "Fresh impact chip", "repair_feasibility": "Excellent", "mobile_service": true, "fraud_risk": "low"}',
  false,
  null,
  false,
  true,
  'Sieger Insurance',
  '{"make": "Jeep", "model": "Grand Cherokee", "year": 2022, "vin": "1C4RJFAG8NC123456", "color": "Red", "mileage": 15000}',
  ARRAY['jeep-chip.jpg'],
  145.00,
  null,
  null,
  null,
  null,
  false,
  'Mobile service scheduled at customer location.',
  'Customer prefers mobile service due to work schedule.'
),
(
  'Kevin Brown',
  'kevin.brown@email.com',
  '+1-555-1005',
  'shop-005',
  'City Glass & Calibration',
  'replacement',
  'windshield_replacement',
  CURRENT_DATE + INTERVAL '4 days',
  '10:15:00',
  'confirmed',
  'scheduled',
  'replacement',
  0.94,
  '{"damage_assessment": "Multiple cracks", "repair_feasibility": "Replacement required", "fraud_risk": "low"}',
  true,
  'Audi ADAS system requires calibration',
  true,
  true,
  'Sieger Insurance',
  '{"make": "Audi", "model": "A4", "year": 2023, "vin": "WAUZZZF47PA123456", "color": "Blue", "mileage": 12000}',
  ARRAY['audi-damage.jpg'],
  1150.00,
  null,
  null,
  null,
  null,
  false,
  'Saturday appointment for windshield replacement.',
  'New Audi requires OEM glass and ADAS calibration.'
),

-- IN PROGRESS JOBS
(
  'Patricia Davis',
  'patricia.davis@email.com',
  '+1-555-2001',
  'shop-001',
  'Elite Auto Glass',
  'replacement',
  'windshield_replacement',
  CURRENT_DATE,
  '08:30:00',
  'confirmed',
  'in_progress',
  'replacement',
  0.89,
  '{"damage_assessment": "Large spider crack", "repair_feasibility": "Replacement needed", "fraud_risk": "low"}',
  false,
  null,
  true,
  true,
  'Sieger Insurance',
  '{"make": "Volkswagen", "model": "Jetta", "year": 2021, "vin": "3VWC57BU8MM123456", "color": "Gray", "mileage": 22000}',
  ARRAY['vw-damage.jpg'],
  725.00,
  NOW() - INTERVAL '2 hours',
  null,
  null,
  null,
  false,
  'Currently installing new windshield.',
  'Job in progress, expected completion in 1 hour.'
),
(
  'Christopher Lee',
  'chris.lee@email.com',
  '+1-555-2002',
  'shop-002',
  'Precision Glass Services',
  'repair',
  'crack_repair',
  CURRENT_DATE,
  '13:00:00',
  'confirmed',
  'in_progress',
  'crack_repair',
  0.85,
  '{"damage_assessment": "Long stress crack", "repair_feasibility": "Repairable with resin", "fraud_risk": "low"}',
  false,
  null,
  false,
  true,
  'Sieger Insurance',
  '{"make": "Subaru", "model": "Outback", "year": 2020, "vin": "4S4BSANC3L3123456", "color": "Green", "mileage": 45000}',
  ARRAY['subaru-crack.jpg'],
  165.00,
  NOW() - INTERVAL '45 minutes',
  null,
  null,
  null,
  false,
  'Resin injection in progress.',
  'Crack repair underway, almost finished.'
),
(
  'Michelle Martinez',
  'michelle.martinez@email.com',
  '+1-555-2003',
  'shop-mobile-01',
  'Mobile Glass Pro',
  'repair',
  'chip_repair',
  CURRENT_DATE,
  '15:30:00',
  'confirmed', 
  'in_progress',
  'chip_repair',
  0.91,
  '{"damage_assessment": "Small bullseye chip", "repair_feasibility": "Perfect for repair", "mobile_service": true, "fraud_risk": "low"}',
  false,
  null,
  false,
  true,
  'Sieger Insurance',
  '{"make": "Mazda", "model": "CX-5", "year": 2022, "vin": "JM3KFBCM8N0123456", "color": "Blue", "mileage": 18000}',
  ARRAY['mazda-chip.jpg'],
  125.00,
  NOW() - INTERVAL '30 minutes',
  null,
  null,
  null,
  false,
  'Mobile technician on-site, repair in progress.',
  'Customer at home, mobile service in progress.'
),

-- CANCELLED JOBS
(
  'Richard Johnson',
  'richard.johnson@email.com',
  '+1-555-3001',
  'shop-001',
  'Elite Auto Glass',
  'replacement',
  'windshield_replacement',
  CURRENT_DATE - INTERVAL '1 day',
  '11:00:00',
  'cancelled',
  'cancelled',
  'replacement',
  0.88,
  '{"damage_assessment": "Extensive damage", "repair_feasibility": "Replacement required", "fraud_risk": "medium"}',
  false,
  null,
  true,
  true,
  'Sieger Insurance',
  '{"make": "Dodge", "model": "Charger", "year": 2019, "vin": "2C3CDXHG2KH123456", "color": "Black", "mileage": 55000}',
  ARRAY['dodge-damage.jpg'],
  650.00,
  null,
  null,
  null,
  null,
  false,
  'Job cancelled - customer found aftermarket option.',
  'Customer decided to go with non-network shop.'
),
(
  'Nancy White',
  'nancy.white@email.com',
  '+1-555-3002',
  'shop-003',
  'Quick Fix Auto Glass',
  'repair',
  'chip_repair',
  CURRENT_DATE - INTERVAL '2 days',
  '14:30:00',
  'cancelled',
  'cancelled',
  'chip_repair',
  0.79,
  '{"damage_assessment": "Small chip", "repair_feasibility": "Repairable", "fraud_risk": "high"}',
  false,
  null,
  false,
  true,
  'Sieger Insurance',
  '{"make": "Kia", "model": "Optima", "year": 2018, "vin": "KNAGV4LD2J5123456", "color": "Silver", "mileage": 67000}',
  ARRAY['kia-chip.jpg'],
  95.00,
  null,
  null,
  null,
  null,
  false,
  'Cancelled due to fraud investigation.',
  'High fraud risk detected, claim cancelled for investigation.'
),
(
  'Daniel Garcia',
  'daniel.garcia@email.com', 
  '+1-555-3003',
  'shop-005',
  'City Glass & Calibration',
  'replacement',
  'windshield_replacement',
  CURRENT_DATE - INTERVAL '3 days',
  '09:45:00',
  'cancelled',
  'cancelled',
  'replacement',
  0.86,
  '{"damage_assessment": "Impact damage", "repair_feasibility": "Replacement needed", "fraud_risk": "low"}',
  true,
  'ADAS calibration required',
  true,
  true,
  'Sieger Insurance',
  '{"make": "Cadillac", "model": "XT5", "year": 2021, "vin": "1GYKNCRS5MZ123456", "color": "White", "mileage": 28000}',
  ARRAY['cadillac-damage.jpg'],
  1275.00,
  null,
  null,
  null,
  null,
  false,
  'Customer cancelled appointment.',
  'Customer decided to delay repair due to personal reasons.'
);