// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsvmigyunbwdefibbpgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzdm1pZ3l1bmJ3ZGVmaWJicGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDQ5NDYsImV4cCI6MjA3MDU4MDk0Nn0.N0ZOb8xifA62nz1mF1Tmjx72Nrs-2WET0QUgNv5Df90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});